# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-15 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20190211_2151'),
        ('rango', '0004_auto_20190211_2213'),
        ('rango', '0004_auto_20190129_1704'),
    ]

    operations = [
    ]
